/*	Copyright (c) 1990, 1991 UNIX System Laboratories, Inc.	*/
/*	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF     	*/
/*	UNIX System Laboratories, Inc.                     	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

/*	Copyright (c) 1990  Intel Corporation	*/
/*	All Rights Reserved	*/

/*	INTEL CORPORATION PROPRIETARY INFORMATION	*/

/*	This software is supplied to AT & T under the terms of a license   */ 
/*	agreement with Intel Corporation and may not be copied nor         */
/*	disclosed except in accordance with the terms of that agreement.   */	

#ident	"@(#)hiint:uts/i386/master.d/sf01/space.c	1.1"

#include "sys/types.h"
#include "sys/param.h"
#include "sys/buf.h"
#include "sys/sdi.h"
#include "sys/scsi.h"
#include "sys/elog.h"
#include "sys/vtoc.h"
#include "sys/sf01.h"
#include "sys/conf.h"
#include "config.h"

int	sf01devflag = D_NEW | D_DMA ;	/* SVR4 Driver Flags */

struct disk	*Sf01_dp;				/* Disk structure pointer	*/
struct job	*Sf01_jp;				/* Job structure pointer	*/

/* Supported devices -- when an entry is added to this array, you must
 * add an entry to the Sf01_drive_index array below and a set
 * of format entries to Sf01_drives below.
 */
struct tc_data Sf01_data[] = { 
	"TEAC    FC-1     HF   01", 1,	/* Embedded SCSI floppy - 3.5" */
	"TEAC    FC-1     GF   01", 1,	/* Embedded SCSI floppy - 5.25" */
	"NCR HC FLEX 0101        ", 4	/* NCR multiple floppy controller */
};

/* Sf01_drive_index maps inquiry strings from Sf01_data to appropriate 
 * indicies in the Sf01_drives array
 * below.  Must have one entry for each entry in the Sf01_data array above.
 */
struct drive_index Sf01_drive_index[] = {
	"TEAC    FC-1     HF   01", 0,	/* TEAC */
	"TEAC    FC-1     GF   01", 0,	/* TEAC */
	"NCR HC FLEX 0101        ", 1	/* NCR multiple floppy controller */
};
int Sf01_drive_index_size = SF01ARRAYSZ(Sf01_drive_index);


/* Future development: The limitation of supporting a maximum of 2
 * drives can be eliminated by allowing the floppy driver to have
 * multiple major numbers, as the hard disk driver does.
 */
struct drv_majors Sf01_majors[] = {
	SF01_BMAJOR_0, SF01_CMAJOR_0
};

char   Sf01_debug[] = {
	0,0,0,0,0,0,0,0,0,0				/* Debug levels			*/
};

int	Sf01_datasz  = DATASZ;			/* Number of supported TC's   	*/

#if defined(SF01_CMAJORS)
int	Sf01_cmajors = SF01_CMAJORS;	/* Number of c major numbers	*/
#else
int	Sf01_cmajors = 1;				/* Default 1 major number	*/
#endif

int	Sf01_jobs    = 8;				/* Number of job structures	*/


/* partition data for each format:
 * CAUTION: order of formats, must match order defined in sf01.h.
 */
struct part_data Sf01_parts[FMT_MAXNUM][PART_MAXNUM] = {
/* Partition: */
/* 0	1		2			3 												*/
0,2400,	0,30,	30,2370,	60,2340,		/* 5h + 5b (all - 1st 2 cyls)	*/
0,720,	0,18,	18,702,		PART_UNDEFINED,PART_UNDEFINED,	/* 5d9 */
0,640,	0,16,	16,624,		8,632,			/* 5d8 + 5d8u (all - 1st track) */
0,320,	0,8,	8,312,		PART_UNDEFINED,PART_UNDEFINED,	/* 5d4 */
0,1280,	0,32,	32,1248,	PART_UNDEFINED,PART_UNDEFINED,	/* 5d16 */
0,1422,	0,18,	18,1404,	PART_UNDEFINED,PART_UNDEFINED,	/* 5q */
0,1440,	0,18,	18,1422,	PART_UNDEFINED,PART_UNDEFINED,	/* 3d */
0,2880,	0,36,	36,2844,	PART_UNDEFINED,PART_UNDEFINED	/* 3h */
};

/* medium type code definitions */
#define EMBMEDTYPE		0x0	/* embedded drives don't require med type set */
#define NCR3MEDTYPE		0x1e
#define NCR5HMEDTYPE	0x1a
#define NCR5QMEDTYPE	0x16
#define NCR5DMEDTYPE	0x12

/* misc variable floppy page parameter definitions */
#define NCRHDSETDEL		0x0
#define NCRTRDY			0x0
#define NCRMO			0x0
#define NCRPIN2			0x3
#define NCRSKIPSPC		0x1	/* skip every other cylinder on low d formats */
#define NCRNOSKIPSPC	0x0	/* access every cylinder */
#define NCRPIN34		0x1	/* Open */
#define NCRPRECOMPLEVEL	0xc	/* 125 ns */
#define NCRMOTONDELAY	0x8 /* motor on delay */
#define NCRPIN4			0x1	/* ready -- old style NCR cards require this */

#define EMBHDSETDEL		0xdc
#define EMBTRDY			0x0
#define EMBMO			0x1
#define EMBLOWDPIN2		0x5
#define EMBHIDPIN2		0xd
#define EMBSKIPSPC		0x2	/* skip every other cylinder on low d formats */
#define EMBNOSKIPSPC	0x1	/* access every cylinder */

/* misc constant floppy page parameter definitions */
#define PP_RESERVED		0x00
#define PP_PAGENUM		0x05
#define PP_LEN			0x1e
#define PP_STARTPRECOMP 0x00
#define PP_STARTRDWRITE	0x00
#define PP_STEPRATE		0x1e
#define PP_PULSEWIDTH	0x00
#define PP_MOTONDELAY	0x04
#define PP_MOTOFFDELAY	0x32
#define PP_SSN			0x01
#define PP_PRECOMPLEVEL	0x00
#define PP_HDLOADDEL	0x00
#define PP_HDUNLOADDEL	0x00
#define PP_PIN34		0x02 /* Disk change */
#define PP_PIN1			0x00
#define PP_PIN4			0x00
#define PP_MEDROT		0x00

/* parameters for each format for each drive on the SCSI bus:
 * CAUTION: order of formats, must match order defined in sf01.h.
 * There must be one set of format entries for each manufacturer
 * in the Sf01_drive_index array above, and each set of entries must
 * be positioned in the Sf01_drives array as specified in the
 * Sf01_drive_index array.
 */
struct drive_data Sf01_drives[][FMT_MAXNUM] = {
/* TEAC EMBEDDED */
/* 5h */
	9,EMBMEDTYPE,
	PP_PAGENUM,PP_RESERVED,PP_LEN,SPDHIGH,2,15,512,80,PP_STARTPRECOMP,
	PP_STARTRDWRITE,PP_STEPRATE,PP_PULSEWIDTH,EMBHDSETDEL,PP_MOTONDELAY,
	PP_MOTOFFDELAY,PP_RESERVED,EMBMO,PP_SSN,EMBTRDY,EMBNOSKIPSPC,
	PP_RESERVED,PP_PRECOMPLEVEL,PP_HDLOADDEL,PP_HDUNLOADDEL,EMBHIDPIN2,
	PP_PIN34,PP_PIN1,PP_PIN4,PP_MEDROT,PP_RESERVED,
/* 5d9 */
	9,EMBMEDTYPE,
	PP_PAGENUM,PP_RESERVED,PP_LEN,SPDLOW,2,9,512,40,PP_STARTPRECOMP,
	PP_STARTRDWRITE,PP_STEPRATE,PP_PULSEWIDTH,EMBHDSETDEL,PP_MOTONDELAY,
	PP_MOTOFFDELAY,PP_RESERVED,EMBMO,PP_SSN,EMBTRDY,EMBSKIPSPC,
	PP_RESERVED,PP_PRECOMPLEVEL,PP_HDLOADDEL,PP_HDUNLOADDEL,EMBLOWDPIN2,
	PP_PIN34,PP_PIN1,PP_PIN4,PP_MEDROT,PP_RESERVED,
/* 5d8 */
	9,EMBMEDTYPE,
	PP_PAGENUM,PP_RESERVED,PP_LEN,SPDLOW,2,8,512,40,PP_STARTPRECOMP,
	PP_STARTRDWRITE,PP_STEPRATE,PP_PULSEWIDTH,EMBHDSETDEL,PP_MOTONDELAY,
	PP_MOTOFFDELAY,PP_RESERVED,EMBMO,PP_SSN,EMBTRDY,EMBSKIPSPC,
	PP_RESERVED,PP_PRECOMPLEVEL,PP_HDLOADDEL,PP_HDUNLOADDEL,EMBLOWDPIN2,
	PP_PIN34,PP_PIN1,PP_PIN4,PP_MEDROT,PP_RESERVED,
/* 5d4 */
	10,EMBMEDTYPE,
	PP_PAGENUM,PP_RESERVED,PP_LEN,SPDLOW,2,4,1024,40,PP_STARTPRECOMP,
	PP_STARTRDWRITE,PP_STEPRATE,PP_PULSEWIDTH,EMBHDSETDEL,PP_MOTONDELAY,
	PP_MOTOFFDELAY,PP_RESERVED,EMBMO,PP_SSN,EMBTRDY,EMBSKIPSPC,
	PP_RESERVED,PP_PRECOMPLEVEL,PP_HDLOADDEL,PP_HDUNLOADDEL,EMBLOWDPIN2,
	PP_PIN34,PP_PIN1,PP_PIN4,PP_MEDROT,PP_RESERVED,
/* 5d16 */
	8,EMBMEDTYPE,
	PP_PAGENUM,PP_RESERVED,PP_LEN,SPDLOW,2,16,256,40,PP_STARTPRECOMP,
	PP_STARTRDWRITE,PP_STEPRATE,PP_PULSEWIDTH,EMBHDSETDEL,PP_MOTONDELAY,
	PP_MOTOFFDELAY,PP_RESERVED,EMBMO,PP_SSN,EMBTRDY,EMBSKIPSPC,
	PP_RESERVED,PP_PRECOMPLEVEL,PP_HDLOADDEL,PP_HDUNLOADDEL,EMBLOWDPIN2,
	PP_PIN34,PP_PIN1,PP_PIN4,PP_MEDROT,PP_RESERVED,
/* 5q */
	9,EMBMEDTYPE,
	PP_PAGENUM,PP_RESERVED,PP_LEN,SPDLOW,2,9,512,80,PP_STARTPRECOMP,
	PP_STARTRDWRITE,PP_STEPRATE,PP_PULSEWIDTH,EMBHDSETDEL,PP_MOTONDELAY,
	PP_MOTOFFDELAY,PP_RESERVED,EMBMO,PP_SSN,EMBTRDY,EMBNOSKIPSPC,
	PP_RESERVED,PP_PRECOMPLEVEL,PP_HDLOADDEL,PP_HDUNLOADDEL,EMBLOWDPIN2,
	PP_PIN34,PP_PIN1,PP_PIN4,PP_MEDROT,PP_RESERVED,
/* 3d */
	9,EMBMEDTYPE,
	PP_PAGENUM,PP_RESERVED,PP_LEN,SPDLOW,2,9,512,80,PP_STARTPRECOMP,
	PP_STARTRDWRITE,PP_STEPRATE,PP_PULSEWIDTH,EMBHDSETDEL,PP_MOTONDELAY,
	PP_MOTOFFDELAY,PP_RESERVED,EMBMO,PP_SSN,EMBTRDY,EMBNOSKIPSPC,
	PP_RESERVED,PP_PRECOMPLEVEL,PP_HDLOADDEL,PP_HDUNLOADDEL,EMBLOWDPIN2,
	PP_PIN34,PP_PIN1,PP_PIN4,PP_MEDROT,PP_RESERVED,
/* 3h */
	9,EMBMEDTYPE,
	PP_PAGENUM,PP_RESERVED,PP_LEN,SPDHIGH,2,18,512,80,PP_STARTPRECOMP,
	PP_STARTRDWRITE,PP_STEPRATE,PP_PULSEWIDTH,EMBHDSETDEL,PP_MOTONDELAY,
	PP_MOTOFFDELAY,PP_RESERVED,EMBMO,PP_SSN,EMBTRDY,EMBNOSKIPSPC,
	PP_RESERVED,PP_PRECOMPLEVEL,PP_HDLOADDEL,PP_HDUNLOADDEL,EMBHIDPIN2,
	PP_PIN34,PP_PIN1,PP_PIN4,PP_MEDROT,PP_RESERVED,

/* NCR */
/* 5h */
	9,NCR5HMEDTYPE,
	PP_PAGENUM,PP_RESERVED,PP_LEN,SPDHIGH,2,15,512,80,PP_STARTPRECOMP,
	PP_STARTRDWRITE,PP_STEPRATE,PP_PULSEWIDTH,NCRHDSETDEL,NCRMOTONDELAY,
	PP_MOTOFFDELAY,PP_RESERVED,NCRMO,PP_SSN,NCRTRDY,NCRNOSKIPSPC,
	PP_RESERVED,NCRPRECOMPLEVEL,PP_HDLOADDEL,PP_HDUNLOADDEL,NCRPIN2,
	NCRPIN34,PP_PIN1,NCRPIN4,PP_MEDROT,PP_RESERVED,
/* 5d9 */
	9,NCR5DMEDTYPE,
	PP_PAGENUM,PP_RESERVED,PP_LEN,SPDMED,2,9,512,40,PP_STARTPRECOMP,
	PP_STARTRDWRITE,PP_STEPRATE,PP_PULSEWIDTH,NCRHDSETDEL,NCRMOTONDELAY,
	PP_MOTOFFDELAY,PP_RESERVED,NCRMO,PP_SSN,NCRTRDY,NCRSKIPSPC,
	PP_RESERVED,NCRPRECOMPLEVEL,PP_HDLOADDEL,PP_HDUNLOADDEL,NCRPIN2,
	NCRPIN34,PP_PIN1,NCRPIN4,PP_MEDROT,PP_RESERVED,
/* 5d8 */
	9,NCR5DMEDTYPE,
	PP_PAGENUM,PP_RESERVED,PP_LEN,SPDMED,2,8,512,40,PP_STARTPRECOMP,
	PP_STARTRDWRITE,PP_STEPRATE,PP_PULSEWIDTH,NCRHDSETDEL,NCRMOTONDELAY,
	PP_MOTOFFDELAY,PP_RESERVED,NCRMO,PP_SSN,NCRTRDY,NCRSKIPSPC,
	PP_RESERVED,NCRPRECOMPLEVEL,PP_HDLOADDEL,PP_HDUNLOADDEL,NCRPIN2,
	NCRPIN34,PP_PIN1,NCRPIN4,PP_MEDROT,PP_RESERVED,
/* 5d4 */
	10,NCR5DMEDTYPE,
	PP_PAGENUM,PP_RESERVED,PP_LEN,SPDMED,2,4,1024,40,PP_STARTPRECOMP,
	PP_STARTRDWRITE,PP_STEPRATE,PP_PULSEWIDTH,NCRHDSETDEL,NCRMOTONDELAY,
	PP_MOTOFFDELAY,PP_RESERVED,NCRMO,PP_SSN,NCRTRDY,NCRSKIPSPC,
	PP_RESERVED,NCRPRECOMPLEVEL,PP_HDLOADDEL,PP_HDUNLOADDEL,NCRPIN2,
	NCRPIN34,PP_PIN1,NCRPIN4,PP_MEDROT,PP_RESERVED,
/* 5d16 */
	8,NCR5DMEDTYPE,
	PP_PAGENUM,PP_RESERVED,PP_LEN,SPDMED,2,16,256,40,PP_STARTPRECOMP,
	PP_STARTRDWRITE,PP_STEPRATE,PP_PULSEWIDTH,NCRHDSETDEL,NCRMOTONDELAY,
	PP_MOTOFFDELAY,PP_RESERVED,NCRMO,PP_SSN,NCRTRDY,NCRSKIPSPC,
	PP_RESERVED,NCRPRECOMPLEVEL,PP_HDLOADDEL,PP_HDUNLOADDEL,NCRPIN2,
	NCRPIN34,PP_PIN1,NCRPIN4,PP_MEDROT,PP_RESERVED,
/* 5q */
	9,NCR5QMEDTYPE,
	PP_PAGENUM,PP_RESERVED,PP_LEN,SPDMED,2,9,512,80,PP_STARTPRECOMP,
	PP_STARTRDWRITE,PP_STEPRATE,PP_PULSEWIDTH,NCRHDSETDEL,NCRMOTONDELAY,
	PP_MOTOFFDELAY,PP_RESERVED,NCRMO,PP_SSN,NCRTRDY,NCRNOSKIPSPC,
	PP_RESERVED,NCRPRECOMPLEVEL,PP_HDLOADDEL,PP_HDUNLOADDEL,NCRPIN2,
	NCRPIN34,PP_PIN1,NCRPIN4,PP_MEDROT,PP_RESERVED,
/* 3d */
	9,NCR3MEDTYPE,
	PP_PAGENUM,PP_RESERVED,PP_LEN,SPDLOW,2,9,512,80,PP_STARTPRECOMP,
	PP_STARTRDWRITE,PP_STEPRATE,PP_PULSEWIDTH,NCRHDSETDEL,NCRMOTONDELAY,
	PP_MOTOFFDELAY,PP_RESERVED,NCRMO,PP_SSN,NCRTRDY,NCRNOSKIPSPC,
	PP_RESERVED,NCRPRECOMPLEVEL,PP_HDLOADDEL,PP_HDUNLOADDEL,NCRPIN2,
	NCRPIN34,PP_PIN1,NCRPIN4,PP_MEDROT,PP_RESERVED,
/* 3h */
	9,NCR3MEDTYPE,
	PP_PAGENUM,PP_RESERVED,PP_LEN,SPDHIGH,2,18,512,80,PP_STARTPRECOMP,
	PP_STARTRDWRITE,PP_STEPRATE,PP_PULSEWIDTH,NCRHDSETDEL,NCRMOTONDELAY,
	PP_MOTOFFDELAY,PP_RESERVED,NCRMO,PP_SSN,NCRTRDY,NCRNOSKIPSPC,
	PP_RESERVED,NCRPRECOMPLEVEL,PP_HDLOADDEL,PP_HDUNLOADDEL,NCRPIN2,
	NCRPIN34,PP_PIN1,NCRPIN4,PP_MEDROT,PP_RESERVED

};
