#	Copyright (c) 1990, 1991 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)dlpi_ether:sys/Makefile	1.1"

#
#  There is nothing to make for dlpi_ether.  The components that use the
#  common STREAMS interface will pull include files from this directory.
#

all:

clobber:

clean:

install:

package:
